name: nesp_sdk_dart_core
description: The nesp software development kit for dart.
version: 0.0.1-dev.8
repository: https://github.com/nespjin/nesp_sdk_dart

environment:
  sdk: ^3.3.0

dependencies:
  get_it: ^7.6.4
  characters: ^1.4.0
  meta: ^1.16.0
  stack_trace: ^1.12.1
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
