name: nesp_sdk_dart_dtx
description: The nesp software development kit for dart.
version: 0.0.1-dev.3
repository: https://github.com/nespjin/nesp_sdk_dart

environment:
  sdk: ^3.3.0

dependencies:
  characters: ^1.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
