name: nesp_sdk_dart_http
description: The Http library for the NESP Dart software development kit.
version: 0.0.1-dev.1
repository: https://github.com/nespjin/nesp_sdk_dart

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
