name: nesp_sdk_dart_file_downloader
description: The nesp software development kit for dart.
version: 0.0.1-dev.4
repository: https://github.com/nespjin/nesp_sdk_dart

environment:
  sdk: ^3.3.0

dependencies:
  nesp_sdk_dart_core: ^0.0.1-dev.8
  nesp_sdk_dart_dtx: ^0.0.1-dev.3
  nesp_sdk_dart_http: ^0.0.1-dev.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
