name: nesp_sdk_dart_concurrent
description: The nesp software development kit for dart.
repository: https://github.com/nespjin/nesp_sdk_dart
version: 0.0.1-dev.1

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
